version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.21.0
    - node@20.11.0
    - python@3.10.8
    - ruby@3.1.4

lint:
  # By sourcing this plugin, repos will enable these linters
  enabled:
    - actionlint@1.6.27
    - bandit@1.7.7
    - black@24.2.0
    - buf-lint@1.29.0
    - buildifier@6.4.0
    - cfnlint@0.86.0
    - checkov@3.2.32
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - eslint@8.56.0
    - git-diff-check
    - gofmt@1.20.4
    - golangci-lint@1.56.2
    - hadolint@2.12.0
    - isort@5.13.2
    - markdownlint@0.39.0
    - markdown-link-check@3.11.2
    - mypy@1.8.0
    - nancy@1.0.45
    - osv-scanner@1.6.2
    - oxipng@9.0.0
    - pragma-once
    - prettier@3.2.5
    - prisma@5.10.2
    - pylint@3.1.0
    - renovate@37.230.0
    - rubocop@1.39.0
    - ruff@0.3.1
    - rustfmt@1.68.2
    - semgrep@1.64.0
    - shellcheck@0.9.0
    - shfmt@3.6.0
    - sort-package-json@2.8.0
    - sql-formatter@15.2.0
    - stylelint@16.2.1:
        packages:
          - stylelint-config-standard-scss@13.0.0
          - stylelint-config-clean-order@5.4.1
    - svgo@3.2.0
    - taplo@0.8.1
    - terrascan@1.19.1
    - trivy@0.49.1
    - trufflehog@3.68.5
    - trunk-toolbox@0.3.1
    - yamllint@1.35.1

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.prettierrc.yaml
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.js
        - configs/svgo.config.js
        - configs/.yamllint.yaml

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

tools:
  enabled:
    - gh@2.45.0
    - gt@1.2.5
