version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.19.5
    - node@18.12.1
    - python@3.10.8
    - ruby@3.1.3

lint:
  downloads:
    - name: trunk-toolbox
      # Our own internal alpha linter
      downloads:
        - os:
            linux: unknown-linux-gnu
            macos: apple-darwin
          cpu:
            x86_64: x86_64
            arm_64: aarch64
          url: https://github.com/trunk-io/toolbox/releases/download/${version}/trunk-toolbox-${version}-${cpu}-${os}.tar.gz

  definitions:
    - name: trunk-toolbox
      download: trunk-toolbox
      files: [ALL]
      commands:
        - output: sarif
          run: trunk-toolbox --upstream ${upstream-ref}
          success_codes: [0]
          read_output_from: stdout
          disable_upstream: true
          target: .
      environment:
        - name: PATH
          list: ["${linter}"]

  # By sourcing this plugin, repos will enable these linters
  enabled:
    - actionlint@1.6.25
    - bandit@1.7.5
    - black@23.7.0
    - buf-lint@1.26.1
    - buildifier@6.3.3
    - cfnlint@0.79.8
    - checkov@2.4.9
    - clang-format@16.0.3
    - clang-tidy@16.0.3
    - clippy@1.71.1
    - eslint@8.48.0
    - git-diff-check
    - gofmt@1.20.4
    - golangci-lint@1.54.2
    - hadolint@2.12.0
    - isort@5.12.0
    - markdownlint@0.35.0
    - mypy@1.5.1
    - nancy@1.0.42
    - osv-scanner@1.3.6
    - oxipng@8.0.0
    - pragma-once
    - prettier@3.0.3
    - prisma@5.2.0
    - pylint@2.17.5
    - renovate@36.78.7
    - rubocop@1.39.0
    - ruff@0.0.287
    - rustfmt@1.68.2
    - semgrep@1.38.2
    - shellcheck@0.9.0
    - shfmt@3.6.0
    - sort-package-json@2.5.1
    - sql-formatter@13.0.0
    - stylelint@15.10.3
    - svgo@3.0.2
    - taplo@0.8.1
    - terrascan@1.18.3
    - trivy@0.44.1
    - trufflehog@3.54.3
    - trunk-toolbox@0.0.1
    - yamllint@1.32.0

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.prettierrc.yaml
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.yaml
        - configs/svgo.config.js
        - configs/.yamllint.yaml

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

tools:
  enabled:
    - gh@2.31.0
    - gt@0.20.22
