version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.21.0
    - node@20.11.0
    - python@3.10.8
    - ruby@3.1.4

lint:
  # By sourcing this plugin, repos will enable these linters
  enabled:
    - actionlint@1.7.1
    - bandit@1.7.9
    - black@24.8.0
    - buf-lint@1.31.0!
    - buildifier@7.1.2
    - cfnlint@1.11.1
    - checkov@3.2.239
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - eslint@8.56.0
    - git-diff-check
    - gofmt@1.20.4
    - golangci-lint@1.60.3
    - hadolint@2.12.0
    - isort@5.13.2
    - markdownlint@0.41.0
    - markdown-link-check@3.12.2
    - mypy@1.11.2
    - nancy@1.0.46
    - osv-scanner@1.8.4
    - oxipng@9.1.2
    - pragma-once
    - prettier@3.3.3
    - prisma@5.19.0
    - pylint@3.2.6
    - renovate@38.58.0
    - rubocop@1.39.0
    - ruff@0.6.3
    - rustfmt@1.68.2
    - semgrep@1.85.0
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - sort-package-json@2.10.1
    - sql-formatter@15.4.1
    - stylelint@16.9.0:
        packages:
          - stylelint-config-standard-scss@13.1.0
          - stylelint-config-clean-order@6.1.0
    - svgo@3.3.2
    - taplo@0.9.3
    - terrascan@1.19.1
    # Disabled until filesystem scanner initialize error resolved.
    # - trivy@0.54.1
    - trufflehog@3.81.10
    - trunk-toolbox@0.4.0
    - yamllint@1.35.1

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.prettierrc.yaml
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.js
        - configs/svgo.config.js
        - configs/.yamllint.yaml

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

tools:
  enabled:
    - gh@2.55.0
    - gt@1.4.3
