version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.24.3
    - node@22.16.0
    - python@3.10.8
    - ruby@3.4.2

lint:
  # By sourcing this plugin, repos will enable these linters
  enabled:
    - actionlint@1.7.8
    - bandit@1.8.6
    - black@25.9.0
    - buf-lint@1.31.0!
    - buildifier@8.2.1
    - cfnlint@1.40.3
    - checkov@3.2.489
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - eslint@8.56.0
    - git-diff-check
    - gofmt@1.20.4
    - golangci-lint@1.64.8
    - hadolint@2.14.0
    - isort@7.0.0
    - markdownlint@0.45.0
    - markdown-link-check@3.14.1
    - mypy@1.18.2
    - nancy@1.0.52
    - osv-scanner@2.2.4
    - oxipng@9.1.5
    - pragma-once
    - prettier@3.6.2
    - prisma@6.18.0
    - pylint@4.0.2
    - renovate@41.167.2
    - rubocop@1.39.0
    - ruff@0.14.3
    - rustfmt@1.68.2
    - semgrep@1.142.0
    - shellcheck@0.11.0
    - shfmt@3.6.0
    - sort-package-json@3.4.0
    - sql-formatter@15.6.10
    - stylelint@16.25.0:
        packages:
          - stylelint-config-standard-scss@16.0.0
          - stylelint-config-clean-order@7.0.0
    - svgo@4.0.0
    - taplo@0.10.0
    - terrascan@1.19.1
    # Disabled until filesystem scanner initialize error resolved.
    # - trivy@0.54.1
    - trufflehog@3.90.12
    - trunk-toolbox@0.5.4
    - yamllint@1.37.1

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.prettierrc.yaml
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.js
        - configs/svgo.config.mjs
        - configs/.yamllint.yaml

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

downloads:
  - name: trunk-analytics-cli
    downloads:
      - os:
          linux: unknown-linux
          macos: apple-darwin
        cpu:
          x86_64: x86_64
          arm_64: aarch64
        url: https://github.com/trunk-io/analytics-cli/releases/download/${version}/trunk-analytics-cli-${cpu}-${os}.tar.gz
tools:
  definitions:
    - name: trunk-analytics-cli
      download: trunk-analytics-cli
      known_good_version: 0.8.1
      shims: [trunk-analytics-cli]
      health_checks:
        - command: trunk-analytics-cli --version
          parse_regex: trunk flakytests ${semver}
  enabled:
    - gh@2.82.1
    - grpcui@1.4.3
    - gt@1.7.5
    - trunk-analytics-cli@0.11.6
