version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.21.0
    - node@20.11.0
    - python@3.10.8
    - ruby@3.1.4

lint:
  # By sourcing this plugin, repos will enable these linters
  enabled:
    - actionlint@1.6.27
    - bandit@1.7.8
    - black@24.4.1
    - buf-lint@1.31.0
    - buildifier@7.1.1
    - cfnlint@0.86.4
    - checkov@3.2.74
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - eslint@8.56.0
    - git-diff-check
    - gofmt@1.20.4
    - golangci-lint@1.57.2
    - hadolint@2.12.0
    - isort@5.13.2
    - markdownlint@0.39.0
    - markdown-link-check@3.11.2
    - mypy@1.10.0
    - nancy@1.0.46
    - osv-scanner@1.7.2
    - oxipng@9.1.1
    - pragma-once
    - prettier@3.2.5
    - prisma@5.13.0
    - pylint@3.1.0
    - renovate@37.322.0
    - rubocop@1.39.0
    - ruff@0.4.1
    - rustfmt@1.68.2
    - semgrep@1.70.0
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - sort-package-json@2.10.0
    - sql-formatter@15.3.1
    - stylelint@16.4.0:
        packages:
          - stylelint-config-standard-scss@13.1.0
          - stylelint-config-clean-order@5.4.2
    - svgo@3.2.0
    - taplo@0.8.1
    - terrascan@1.19.1
    - trivy@0.50.4
    - trufflehog@3.74.0
    - trunk-toolbox@0.3.1
    - yamllint@1.35.1

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.prettierrc.yaml
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.js
        - configs/svgo.config.js
        - configs/.yamllint.yaml

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

tools:
  enabled:
    - gh@2.48.0
    - gt@1.3.3
