version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.24.3
    - node@22.16.0
    - python@3.10.8
    - ruby@3.1.4

lint:
  # By sourcing this plugin, repos will enable these linters
  enabled:
    - actionlint@1.7.7
    - bandit@1.8.3
    - black@25.1.0
    - buf-lint@1.31.0!
    - buildifier@8.2.0
    - cfnlint@1.34.2
    - checkov@3.2.432
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - eslint@8.56.0
    - git-diff-check
    - gofmt@1.20.4
    - golangci-lint@1.64.8
    - hadolint@2.12.1-beta
    - isort@6.0.1
    - markdownlint@0.45.0
    - markdown-link-check@3.13.7
    - mypy@1.15.0
    - nancy@1.0.48
    - osv-scanner@2.0.2
    - oxipng@9.1.5
    - pragma-once
    - prettier@3.5.3
    - prisma@6.8.2
    - pylint@3.3.7
    - renovate@40.0.6
    - rubocop@1.39.0
    - ruff@0.11.11
    - rustfmt@1.68.2
    - semgrep@1.116.0
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - sort-package-json@3.0.0
    - sql-formatter@15.6.2
    - stylelint@16.19.1:
        packages:
          - stylelint-config-standard-scss@15.0.1
          - stylelint-config-clean-order@7.0.0
    - svgo@3.3.2
    - taplo@0.9.3
    - terrascan@1.19.1
    # Disabled until filesystem scanner initialize error resolved.
    # - trivy@0.54.1
    - trufflehog@3.88.33
    - trunk-toolbox@0.5.4
    - yamllint@1.37.1

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.prettierrc.yaml
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.js
        - configs/svgo.config.mjs
        - configs/.yamllint.yaml

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

downloads:
  - name: trunk-analytics-cli
    downloads:
      - os:
          linux: unknown-linux
          macos: apple-darwin
        cpu:
          x86_64: x86_64
          arm_64: aarch64
        url: https://github.com/trunk-io/analytics-cli/releases/download/${version}/trunk-analytics-cli-${cpu}-${os}.tar.gz
tools:
  definitions:
    - name: trunk-analytics-cli
      download: trunk-analytics-cli
      known_good_version: 0.8.1
      shims: [trunk-analytics-cli]
      health_checks:
        - command: trunk-analytics-cli --version
          parse_regex: trunk flakytests ${semver}
  enabled:
    - gh@2.73.0
    - grpcui@1.4.3
    - gt@1.6.2
    - trunk-analytics-cli@0.8.1
