version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.24.3
    - node@22.16.0
    - python@3.10.8
    - ruby@3.4.2

lint:
  # By sourcing this plugin, repos will enable these linters
  enabled:
    - actionlint@1.7.12
    - bandit@1.9.4
    - black@26.5.1
    - buf-lint@1.31.0!
    - buildifier@8.5.1
    - cfnlint@1.56.0
    - checkov@3.3.16
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - eslint@8.56.0
    - git-diff-check
    - gofmt@1.20.4
    - golangci-lint2@2.13.2
    - hadolint@2.15.1
    - isort@9.0.1
    - markdownlint@0.49.1
    - markdown-link-check@3.15.0
    - mypy@2.3.1
    - nancy@2.1.0
    - osv-scanner@2.5.1
    - oxipng@10.2.1
    - pragma-once
    - prettier@3.9.6
    - prisma@8.0.0-rc.13
    - pylint@4.0.8
    - renovate@44.66.1
    - rubocop@1.39.0
    - ruff@0.16.6
    - rustfmt@1.68.2
    - semgrep@1.176.1
    - shellcheck@0.11.0
    - shfmt@3.6.0
    - sort-package-json@4.0.0
    - sql-formatter@15.8.2
    - stylelint@17.15.0:
        packages:
          - stylelint-config-standard-scss@17.0.0
          - stylelint-config-clean-order@10.0.0
    - svgo@4.1.0
    - taplo@0.10.0
    - terrascan@1.19.9
    # Disabled until filesystem scanner initialize error resolved.
    # - trivy@0.54.1
    - trufflehog@3.97.4
    - trunk-toolbox@0.7.0
    - yamllint@1.38.0

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.prettierrc.yaml
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.js
        - configs/svgo.config.mjs
        - configs/.yamllint.yaml

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

downloads:
  - name: trunk-analytics-cli
    downloads:
      - os:
          linux: unknown-linux
          macos: apple-darwin
        cpu:
          x86_64: x86_64
          arm_64: aarch64
        url: https://github.com/trunk-io/analytics-cli/releases/download/${version}/trunk-analytics-cli-${cpu}-${os}.tar.gz
tools:
  definitions:
    - name: trunk-analytics-cli
      download: trunk-analytics-cli
      known_good_version: 0.12.5
      shims: [trunk-analytics-cli]
      health_checks:
        - command: trunk-analytics-cli --version
          parse_regex: trunk-analytics-cli ${semver}
  enabled:
    - gh@2.100.0
    - grpcui@1.5.4
    - gt@1.8.6
    - trunk-analytics-cli@0.15.4
