version: 0.1
required_trunk_version: ">=1.7.1-beta.9"

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.24.3
    - node@22.16.0
    - python@3.10.8
    - ruby@3.4.2

lint:
  # By sourcing this plugin, repos will enable these linters
  enabled:
    - actionlint@1.7.9
    - bandit@1.9.2
    - black@25.11.0
    - buf-lint@1.31.0!
    - buildifier@8.2.1
    - cfnlint@1.42.0
    - checkov@3.2.495
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - eslint@8.56.0
    - git-diff-check
    - gofmt@1.20.4
    - golangci-lint@2.7.1
    - hadolint@2.14.0
    - isort@7.0.0
    - markdownlint@0.46.0
    - markdown-link-check@3.14.2
    - mypy@1.19.0
    - nancy@1.0.52
    - osv-scanner@2.3.0
    - oxipng@9.1.5
    - pragma-once
    - prettier@3.7.4
    - prisma@7.1.0
    - pylint@4.0.4
    - renovate@42.37.1
    - rubocop@1.39.0
    - ruff@0.14.8
    - rustfmt@1.68.2
    - semgrep@1.144.1
    - shellcheck@0.11.0
    - shfmt@3.6.0
    - sort-package-json@3.5.0
    - sql-formatter@15.6.10
    - stylelint@16.26.1:
        packages:
          - stylelint-config-standard-scss@16.0.0
          - stylelint-config-clean-order@8.0.0
    - svgo@4.0.0
    - taplo@0.10.0
    - terrascan@1.19.9
    # Disabled until filesystem scanner initialize error resolved.
    # - trivy@0.54.1
    - trufflehog@3.91.2
    - trunk-toolbox@0.5.4
    - yamllint@1.37.1

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.prettierrc.yaml
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.js
        - configs/svgo.config.mjs
        - configs/.yamllint.yaml

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit

downloads:
  - name: trunk-analytics-cli
    downloads:
      - os:
          linux: unknown-linux
          macos: apple-darwin
        cpu:
          x86_64: x86_64
          arm_64: aarch64
        url: https://github.com/trunk-io/analytics-cli/releases/download/${version}/trunk-analytics-cli-${cpu}-${os}.tar.gz
tools:
  definitions:
    - name: trunk-analytics-cli
      download: trunk-analytics-cli
      known_good_version: 0.8.1
      shims: [trunk-analytics-cli]
      health_checks:
        - command: trunk-analytics-cli --version
          parse_regex: trunk flakytests ${semver}
  enabled:
    - gh@2.83.1
    - grpcui@1.4.3
    - gt@1.7.10
    - trunk-analytics-cli@0.11.8
