name: Weekly
on:
  schedule:
    # Weekly at midnight M/F morning
    - cron: 0 8 * * 1,5
  workflow_dispatch: {}

permissions: read-all

jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create App Token for TrunkBuild App (Internal)
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.TRUNK_OPEN_PR_APP_ID }}
          private_key: ${{ secrets.TRUNK_OPEN_PR_APP_PRIVATE_KEY }}

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@bd686325615e9cf5a4ef98372ba94a472f9b5238
        with:
          add-paths: plugin.yaml
          arguments: --apply-to=plugin.yaml -n
          github-token: ${{ steps.generate-token.outputs.token }}
          reviewers: TylerJang27
